"""
prompt_answers.py

Wrapper around

PUT /api/reports/{reportId}/instances/{instanceId}/prompts/answers

Submits answers for prompted reports.
"""

import json


def answer_report_prompts(
    client,
    report_id,
    instance_id,
    payload
):
    """
    Submit prompt answers.

    Parameters
    ----------
    client : MSTRClient

    report_id : str

    instance_id : str

    payload : dict
        Prompt answer payload generated by PromptEngine.

    Returns
    -------
    bool
    """

    endpoint = (
        f"/reports/"
        f"{report_id}"
        f"/instances/"
        f"{instance_id}"
        f"/prompts/answers"
    )

    print("\nCalling REST API")
    print("-" * 60)
    print(f"Endpoint : {endpoint}")

    print("\n========== PROMPT PAYLOAD ==========")
    print(
        json.dumps(
            payload,
            indent=4
        )
    )
    print("====================================")

    response = client.put(
        endpoint,
        json=payload,
        headers={
            "Accept": "application/json",
            "Content-Type": "application/json"
        }
    )

    print("\nHTTP Status :", response.status_code)

    if response.status_code != 204:

        print("\n========== SERVER RESPONSE ==========")
        print(response.status_code)

        try:
            print(
                json.dumps(
                    response.json(),
                    indent=4
                )
            )
        except Exception:
            print(response.text)

        print("====================================")

        raise Exception(
            f"Unable to answer prompts ({response.status_code})"
        )

    return True